# See also:
# - https://github.com/actions/runner/issues/774
# - https://help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push
# - https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
# - https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: "[skip ci]" on Actions

on: [push, pull_request]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    steps:
      - run: |
          echo 'github.event_name: ${{ github.event_name }}'
          echo 'github.event:'
          echo '${{ toJson(github.event) }}'
  build:
    needs: check_skip
    runs-on: ubuntu-latest
    steps:
      - run: echo 'I lost the game.'
